### ISSUE TITLE
Flight Data Scraper not working

### ISSUE THREAD

**Issue by jimz7** [OSU-NLP-Group/GroundCocoa#1]
I think `python scrape_flight_data.py` is not working properly. 
<img width="325" alt="image" src="https://github.com/OSU-NLP-Group/GroundCocoa/assets/37298719/f85ed1d6-0627-4ed4-b30a-d92c399a77bf">

**Comment by HarshKohli** [comment]
Hi,

Thank you for raising this issue. This typically happens when your chromedriver and chrome path are not properly configured. I have updated the instructions on the readme and modified some selenium configuration code. Remember to change the two paths in the constants.py to the location of your local chrome and chromedriver executables. Feel free to reach out if the issue persists!
